src/beans/Priv.java
package beans;

import java.io.Serializable;
import java.util.ArrayList;

import staticData.Menu;

public class Priv implements Serializable {

    // Bean properties
    private String             privName;
    private String             privDescrition;
    private ArrayList<String>  groupNames;
    private ArrayList<Integer> menuPaths;
    private ArrayList<String>  menuNames;

    /*----------------------------------------GETTERS AND SETTERS ---------------------------------------------------------*/

    public String getPrivName() {
        return privName;
    }

    public void setPrivName( String privName ) {
        this.privName = privName;
    }

    public String getPrivDescription() {
        return privDescrition;
    }

    public void setPrivDescription( String privDescrition ) {
        this.privDescrition = privDescrition;
    }

    public ArrayList<String> getGroupNames() {
        return groupNames;
    }

    public void setGroupNames( ArrayList<String> groupNames ) {
        this.groupNames = groupNames;
    }

    public ArrayList<Integer> getMenuPaths() {
        return menuPaths;
    }

    public void setMenuPaths( ArrayList<Integer> menuPaths ) {
        this.menuPaths = menuPaths;
    }

    public void addMenuPath( int menuPath ) {
        this.menuPaths.add( menuPath );
    }

    public void addGroupName( String groupName ) {
        this.groupNames.add( groupName );
    }

    public ArrayList<String> getMenuNames() {
        return menuNames;
    }

    public void setMenuNames( ArrayList<String> menuNames ) {
        this.menuNames = menuNames;
    }

    // convert menuPath from Integer to String
    public void convertPaths() {
        ArrayList<String> menuNames = new ArrayList<String>();
        for ( int i : menuPaths ) {
            menuNames.add( Menu.getMenuName( i ) );
        }
        this.setMenuNames( menuNames );
    }

}

src/beans/User.java
package beans;

import java.io.Serializable;
import java.util.ArrayList;

import org.joda.time.DateTime;

public class User implements Serializable {

    // Bean properties
    private String            username;
    private String            password;
    private String            firstName;
    private String            lastName;
    private String            email;
    private String            phone;
    private String            photoURL;
    private String            address;
    private int               sex;
    private String            className;
    private DateTime          regDate;
    private DateTime          birthDate;
    private ArrayList<String> groupNames;
    private ArrayList<String> courseNames;

    // Contructor
    public User() {
        super();
        ArrayList<String> list = new ArrayList<String>();
        this.courseNames = list;

    }

    /*----------------------------------------GETTERS AND SETTERS ---------------------------------------------------------*/
    public String getPassword() {
        return password;
    }

    public void setPassword( String password ) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName( String firstName ) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName( String lastName ) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail( String email ) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }

    public String getPhotoURL() {
        return photoURL;
    }

    public void setPhotoURL( String photoURL ) {
        this.photoURL = photoURL;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress( String address ) {
        this.address = address;
    }

    public int getSex() {
        return sex;
    }

    public void setSex( int sex ) {
        this.sex = sex;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername( String username ) {
        this.username = username;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName( String className ) {
        this.className = className;
    }

    public DateTime getRegDate() {
        return regDate;
    }

    public void setRegDate( DateTime regDate ) {
        this.regDate = regDate;
    }

    public DateTime getBirthDate() {
        return birthDate;
    }

    public void setBirthDate( DateTime d ) {
        this.birthDate = d;
    }

    public ArrayList<String> getGroupNames() {
        return groupNames;
    }

    public void setGroupNames( ArrayList<String> groupNames ) {
        this.groupNames = groupNames;
    }

    public ArrayList<String> getCourseNames() {
        return courseNames;
    }

    public void setCourseNames( ArrayList<String> courseIDs ) {
        this.courseNames = courseIDs;
    }

    // Adds a course in user's course list
    public void addCourseName( String courseName ) {
        this.courseNames.add( courseName );
    }

    // Adds a group in user's group list
    public void addGroupName( String groupName ) {
        this.groupNames.add( groupName );
    }

    // Removes a course from user's course list
    public void removeCourse( String courseName ) {
        this.courseNames.remove( courseName );
    }

}

src/servlets/KmeansServlet.java
package servlets;

//Controller for KMeans Algorithms 

import java.io.IOException;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import utilities.UtilitiesForm;
import beans.KmeansDataType;
import beans.User;
import dao.DAOFactory;
import dao.TransactionTableDao;
import dao.KmeansDataDao;
import dataMining.Kmeans;

@WebServlet( "/kMeans" )
public class KmeansServlet extends HttpServlet {

    public static final String  CONF_DAO_FACTORY   = "daofactory";
    public static final String  VIEW               = "/WEB-INF/kMeans.jsp";

    public static final String  KMEANS_DATA_ATT    = "kmeansData";
    public static final String  KMEANS_CLUSTER_ATT = "centers";
    private static final String INDIVIDUAL_FIELD   = "Individual";
    private static final String CLUSTER_FIELD      = "Clusters";
    public static final String  USER_SESSION_ATT   = "userSession";

    private KmeansDataDao       kmeansDataDao;
    private TransactionTableDao        transactionTableDao;
    private UtilitiesForm       util               = new UtilitiesForm();

    public void init() throws ServletException {
        this.kmeansDataDao = ( (DAOFactory) getServletContext().getAttribute( CONF_DAO_FACTORY ) ).getKmeansDataDao();
        this.transactionTableDao = ( (DAOFactory) getServletContext().getAttribute( CONF_DAO_FACTORY ) ).getTransactionTableDao();

    }

    public void doGet( HttpServletRequest request, HttpServletResponse response ) throws ServletException, IOException {

        this.getServletContext().getRequestDispatcher( VIEW ).forward( request, response );
    }

    public void doPost( HttpServletRequest request, HttpServletResponse response ) throws ServletException, IOException {
        KmeansDataType[] dataArray = null;

        int nbClusters;
        if ( util.getFieldValue( request, INDIVIDUAL_FIELD ).equalsIgnoreCase( "User" ) ) {
            dataArray = kmeansDataDao.getUserActivity();
            if ( kmeansDataDao.countActiveUsers() < util.getIntValue( request, CLUSTER_FIELD ) ) {
                nbClusters = 1;
            } else {
                nbClusters = util.getIntValue( request, CLUSTER_FIELD );
            }
        } else {
            dataArray = kmeansDataDao.getGroupActivity();
            if ( kmeansDataDao.countActiveGroups() < util.getIntValue( request, CLUSTER_FIELD ) ) {
                nbClusters = 1;
            } else {
                nbClusters = util.getIntValue( request, CLUSTER_FIELD );
            }
        }
        Kmeans kmeans = new Kmeans( dataArray, nbClusters );
        kmeans.calculateClusters();

        /* Session retrieving from the request */
        HttpSession session = request.getSession();
        User userSession = new User();
        // userSession = user logged onn this session
        userSession = (User) session.getAttribute( USER_SESSION_ATT );
        // New action saved in database
        transactionTableDao.addTransaction( userSession.getUsername(), "Kmeans Algorithm" );

        ArrayList<KmeansDataType>[] clusteredData = kmeans.getClusters();
        double[][] clusterCenters = kmeans.getClusterCenters();

        request.setAttribute( KMEANS_DATA_ATT, clusteredData );
        request.setAttribute( KMEANS_CLUSTER_ATT, clusterCenters );

        this.getServletContext().getRequestDispatcher( VIEW ).forward( request, response );
    }

}

src/servlets/NaiveBayesServlet.java
package servlets;

//Controller of Naive Bayes algorithms

import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import utilities.UtilitiesForm;
import weka.core.Attribute;
import beans.User;
import dao.DAOFactory;
import dao.TransactionTableDao;
import dao.NaiveBayesDao;
import dao.UserDao;
import dataMining.NaiveBayesClass;

@WebServlet( "/naiveBayes" )
public class NaiveBayesServlet extends HttpServlet {

    public static final String CONF_DAO_FACTORY    = "daofactory";
    public static final String VIEW                = "/WEB-INF/naiveBayes.jsp";
    public static final String STUDENT_REQUEST_ATT = "students";
    public static final String RESULT              = "result";
    public static final String USER                = "selectedUser";
    public static final String MAP_RESULT          = "mapResult";
    public static final String USER_SESSION_ATT    = "userSession";

    public static final String STUDENT_FIELD       = "students";

    public static final String KMEANS_DATA_ATT     = "kmeansData";

    private UserDao            userDao;
    private NaiveBayesDao      naiveBayesDao;
    private TransactionTableDao       transactionTableDao;
    private UtilitiesForm      util                = new UtilitiesForm();

    public void init() throws ServletException {

        this.userDao = ( (DAOFactory) getServletContext().getAttribute( CONF_DAO_FACTORY ) ).getUserDao();
        this.naiveBayesDao = ( (DAOFactory) getServletContext().getAttribute( CONF_DAO_FACTORY ) ).getNaiveBayesDao();
        this.transactionTableDao = ( (DAOFactory) getServletContext().getAttribute( CONF_DAO_FACTORY ) ).getTransactionTableDao();

    }

    public void doGet( HttpServletRequest request, HttpServletResponse response ) throws ServletException, IOException {

        // Student list retrieving and saving in the request as a
        // LinkedHashMap(key = username)
        List<User> listeUser = userDao.listGroup( "student" );
        Map<String, User> mapStudents = new LinkedHashMap<String, User>();
        for ( User stu : listeUser ) {
            mapStudents.put( stu.getUsername(), stu );
        }
        request.setAttribute( STUDENT_REQUEST_ATT, mapStudents );

        // Naive Bayes page display
        this.getServletContext().getRequestDispatcher( VIEW ).forward( request, response );
    }

    public void doPost( HttpServletRequest request, HttpServletResponse response ) throws ServletException, IOException {

        // Limits number of digits
        NumberFormat nf = new DecimalFormat( "0.##" );

        String result = "Error";

        // User name retrieving from the form
        String studentName = util.getFieldValue( request, STUDENT_FIELD );
        // User informations retrieving thanks to the username.
        User user = userDao.find( studentName );

        // Creates a naive bayes classifier (from dataMining package)
        NaiveBayesClass classifier = new NaiveBayesClass( user, userDao, naiveBayesDao );

        double[] likelihood = null;
        Attribute courseAttribute = null;

        try {
            // Runs the naive Bayes algorithm and save the result
            result = classifier.courseAdvice( user );
            // Runs the naive Bayes algorithm
            likelihood = classifier.getfDistribution();
            // Course list retrieving (attribute, vector of course names)
            courseAttribute = classifier.getCourse();

            /* Session retrieving from the request */
            HttpSession session = request.getSession();
            User userSession = new User();
            // userSession = user logged onn this session
            userSession = (User) session.getAttribute( USER_SESSION_ATT );
            // New action saved in database
            transactionTableDao.addTransaction( userSession.getUsername(), "Naive Bayes Algorithm" );

        } catch ( Exception e ) {
            e.printStackTrace();
        }

        if ( likelihood != null || courseAttribute != null )// If the algorithm
                                                            // returns a result
        {
            HashMap<String, String> mapCourseLikelihood = new HashMap<String, String>();
            // Saving likelihoods in a map (key = course name, value =
            // likelihood)
            for ( int i = 0; i < likelihood.length; i++ )
            {
                mapCourseLikelihood.put( courseAttribute.value( i ), nf.format( likelihood[i] * 100 ) );
            }
            request.setAttribute( MAP_RESULT, mapCourseLikelihood );
        }

        request.setAttribute( USER, studentName );
        request.setAttribute( RESULT, result );

        // if mapStudents is not created yet
        if ( request.getAttribute( STUDENT_REQUEST_ATT ) == null ) {
            // Student list retrieving and saving in the request as a
            // LinkedHashMap(key = username)
            List<User> listeUser = userDao.listGroup( "student" );
            Map<String, User> mapStudents = new HashMap<String, User>();
            for ( User stu : listeUser ) {
                mapStudents.put( stu.getUsername(), stu );
            }
            request.setAttribute( STUDENT_REQUEST_ATT, mapStudents );
        }

        // Naive Bayes page loads again
        this.getServletContext().getRequestDispatcher( VIEW ).forward( request, response );

    }
}

WebContent/WEB-INF/createCourse.jsp
<%--Course creation or modification page--%>
<%--Value of each field is the value registered in the course bean. If it's a creation page nothing appears in the fields,
if it's a modification page or if this page is displayed after an error
all the registered values appear--%>
<%--After each field, field's error appears if there is one --%>

<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page import="java.util.List" %>


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <c:set var="modif" value="true" />
        <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
       			<title>Create a course</title>
        	</c:when>
        	<c:otherwise>
        		<title>Modify a course</title>
        	</c:otherwise>
        </c:choose>
        <link type="text/css" rel="stylesheet" href="<c:url value="/inc/design.css"/>" />
    </head>
    <body>
        <c:import url="/inc/menu.jsp" />
        <br />
       
        <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
        		<h1>Create a course</h1>
        	</c:when>
        	<c:otherwise>
        		<h1>Modify ${course.courseName}</h1>
        	</c:otherwise>
        </c:choose>
       		<h3>Please, fill the following form and validate</h3>
        <div id="normalForm">
            <form method="post" action="<c:url value="/courseCreation"/>" >
                <fieldset>
                    <legend>Course Information</legend>
                    <label for="courseName">Name </label>
                    <c:choose>
        				<c:when test="${ !requestScope.modify eq modif }">
							<input type="text" id="courseName" name="courseName" value="<c:out value="${course.courseName}"/>" size="30" maxlength="30" />
						</c:when>
        				<c:otherwise>							
							<input type="text" id="courseName" name="courseName"  disabled="disabled" value="<c:out value="${course.courseName}"/>" size="30" maxlength="30" />
							<p class="hidden"><input type="text" id="courseName" name="courseName" value="<c:out value="${course.courseName}"/>" size="30" maxlength="30" /></p>
						
						</c:otherwise>
        			</c:choose>
					<span class="error">${form.errors['courseName']}</span>
					<br />
					<br />

					<label for="courseDescription">Description</label>
					<TEXTAREA name="courseDescription" id="courseDescription" rows="5" cols="28" ><c:out value="${course.courseDescription}"/></TEXTAREA>
					<span class="error">${form.errors['courseDescription']}</span>
					<br />
					<br />
					
					<label for="courseYear">Course Year</label>
					<input type="number" name="courseYear" id="courseYear"  value="<c:out value="${course.courseYear}"/>" required/>
					<span class="error">${form.errors['courseYear']}</span>
					<br />
					<br />
					
<%--User has to affect a teacher to a course, but if the user is a teacher, he will be automatically affected to courses he creates. --%>					
					
					<c:set var="bool" value="true" />
					<c:forEach var="item" items="${sessionScope.userSession.groupNames}">
						<c:if test="${item ne 'Teacher'}">
							<c:set var="bool" value="false" />
							<label for="teacher">Teacher :</label>
							<c:choose>
		            			<c:when test="${ empty requestScope.teachers }">
		                		<p class="error">No teachers in database</p>
		            			</c:when>
		            			<c:otherwise>
		            				<select name="teacher" id = "teacher" >																				
				                		<c:forEach items="${ requestScope.teachers }" var="mapTeachers" varStatus="boucle">
				                    		<option value='<c:out value="${mapTeachers.value.username}"/>'><c:out value="${mapTeachers.value.username}"/></option>                    
				                		</c:forEach>
				                	</select>
                				</c:otherwise>
        					</c:choose>
        				</c:if>
        				</c:forEach>
        				
        				<c:if test="${bool eq 'true' }">
        				<p class="hidden">
        					<select name="teacher" id = "teacher" >																				
				                    		<option value='<c:out value="${sessionScope.userSession.username}"/>'><c:out value="${sessionScope.userSession.username}"/></option>                    
				            </select>
				       </p>
				       </c:if>
            		<span class="error">${form.errors['teacher']}</span>
				</fieldset>
                 
                <p class="info">${ form.result }</p>
                <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
        				<input type="submit" name="Create" value="Create"  />
        			</c:when>
        			<c:otherwise>
        				<input type="submit" name="Create" value="Modify"  />
        			</c:otherwise>
        		</c:choose>
                <input type="reset" value="Reset all" /> <br />
            </form>
        </div>
    </body>
</html>

WebContent/WEB-INF/createGroup.jsp
<%--Group creation or modification page--%>
<%--Value of each field is the value registered in the group bean. If it's a creation page nothing appears in the fields,
if it's a modification page or if this page is displayed after an error
all the registered values appear--%>
<%--After each field, field's error appears if there is one --%>

<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page import="java.util.List" %>


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <c:set var="modif" value="true" />
        <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
       			<title>Create a group</title>
        	</c:when>
        	<c:otherwise>
        		<title>Modify a group</title>
        	</c:otherwise>
        </c:choose>
        <link type="text/css" rel="stylesheet" href="<c:url value="/inc/design.css"/>" />
    </head>
    <body>
        <c:import url="/inc/menu.jsp" />
        <br />
        <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
        		<h1>Create a group</h1>
        	</c:when>
        	<c:otherwise>
        		<h1>Modify ${group.groupName} Group</h1>
        	</c:otherwise>
        </c:choose>
        	
       		<h3>Please, fill the following form and validate</h3>
        <div id="normalForm">
            <form method="post" action="<c:url value="/groupCreation"/>" >
                <fieldset>
                    <legend>Group Information</legend>
                    <label for="groupName">Name </label>
					<c:choose>
        				<c:when test="${ !requestScope.modify eq modif }">
							<input type="text" id="groupName" name="groupName" value="<c:out value="${group.groupName}"/>" size="30" maxlength="30" />
						</c:when>
        				<c:otherwise>							
							<input type="text" id="groupName" name="groupName" value="<c:out value="${group.groupName}" />" size="30" maxlength="30" disabled="disabled"/>
							<p class="hidden"><input type="text" id="groupName" name="groupName" value="<c:out value="${group.groupName}"/>" size="30" maxlength="30" /></p>
						
						</c:otherwise>
        			</c:choose>
					<span class="error">${form.errors['groupName']}</span>
					<br />
					<br />

					<label for="groupDescription">Description</label>
					<TEXTAREA name="groupDescription" id="groupDescription" rows="5" cols="28" ><c:out value="${group.groupDescription}"/></TEXTAREA>
					<span class="error">${form.errors['groupDescription']}</span>
					<br />
					<br />
					
					<label for="privs">Please assign privileges<br /> to this group</label>
					<c:choose>
            			<c:when test="${ empty requestScope.privs }">
                		<p class="error">No privileges in database</p>
            			</c:when>
            			<c:otherwise>
		                    <select name="privileges" id = "privileges" multiple="multiple" >																				
								<%-- Parcours de la Map des clients en session, et utilisation de l'objet varStatus. --%>
		                		<c:forEach items="${ requestScope.privs }" var="mapPrivs" varStatus="boucle">
		                    		<option value='<c:out value="${mapPrivs.value.privName}"/>'><c:out value="${mapPrivs.value.privName}"/></option>                    
		                		</c:forEach>
		                	</select>
		                	<span class="error">${form.errors['privileges']}</span>
		                	
                		</c:otherwise>
        			</c:choose>
				</fieldset>
                 
                <p class="info">${ form.result }</p>
                <c:choose>
        			<c:when test="${ !requestScope.modify eq modif }">
        				<input type="submit" name="Create" value="Create"  />
        			</c:when>
        			<c:otherwise>
        				<input type="submit" name="Create" value="Modify"  />
        			</c:otherwise>
        		</c:choose>
                
                <input type="reset" value="Reset all" /> <br />
            </form>
        </div>
    </body>
</html>

WebContent/WEB-INF/createStudent.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <c:set var="modif" value="true" />
         <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
        	<title>Create a Student</title>
        	</c:when>
        	<c:otherwise>
        		<title>Modify student</title>
        	</c:otherwise>
        </c:choose>
        <link type="text/css" rel="stylesheet" href="<c:url value="/inc/design.css"/>" />
        
    </head>
    <body>
        <c:import url="/inc/menu.jsp" />
        <br />
        <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
        		<h1>Create a student</h1>
        	</c:when>
        	<c:otherwise>
        		<h1>Modify ${user.username}</h1>
        	</c:otherwise>
        </c:choose>
       		<h3>Please, fill the following form and validate</h3>
        <div id="normalForm">
            <form method="post" action="<c:url value="/studentCreation"/>" enctype="multipart/form-data">
                <fieldset>
                    <legend>User Information</legend>
                    <%--Here is the import of the user form --%>
                    <c:import url="user_form.jsp" />
                    <%--On this page, user can just create a student so he does not affect a group,
                      but to use the same servlet as the user creation, we need a drop-down list just with Student and hide it --%>
                    <br />
                    
                    	<p class="hidden">
		        			<select name="groups" id = "groups"  required>																				
		                    <option  value='Student' selected="selected" >Student</option>                    
			                </select>
				       </p>       							                		
                </fieldset>  
                <p class="info">${ form.result }</p>
                 <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
        				<input type="submit" name = "Create" value="Create"  /> 			
        			</c:when>
        			<c:otherwise>
        				<input type="submit" name="Create" value="Modify"  />
        			</c:otherwise>
        		</c:choose>
                <input type="reset" value="Reset all" /> <br />
            </form>
        </div>
    </body>
</html>

WebContent/WEB-INF/createTeacher.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <c:set var="modif" value="true" />
        <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
        	<title>Create a teacher</title>
        	</c:when>
        	<c:otherwise>
        		<title>Modify teacher</title>
        	</c:otherwise>
        </c:choose>
        <link type="text/css" rel="stylesheet" href="<c:url value="/inc/design.css"/>" />
        
    </head>
    <body>
        <c:import url="/inc/menu.jsp" />
        <br />
       <c:choose>
        	<c:when test="${ !requestScope.modify eq modif }">
        		<h1>Create a teacher</h1>
        	</c:when>
        	<c:otherwise>
        		<h1>Modify ${user.username}</h1>
        	</c:otherwise>
        </c:choose>
       		<h3>Please, fill the following form and validate</h3>
        <div id="normalForm">
            <form method="post" action="<c:url value="/teacherCreation"/>" enctype="multipart/form-data">
                <fieldset>
                    <legend>User Information</legend>
                    <%--Here is the import of the user form --%>
                    <c:import url="user_form.jsp" />
                    <br />
                    <%--On this page, user can just create a teacher so he does not affect a group,
                      but to use the same servlet as the user creation, we need a drop-down list just with Teacher and hide it --%>
                    
                    	<p class="hidden">
                    	<label for="groups">Please assign groups<br /> to the user</label>                                      
	                     <select name="groups" id = "groups"  required>																				
				                    <option  value='Teacher' selected="selected" >Teacher</option>                    
				         </select>
				         </p>
                </fieldset>  
                <p class="info">${ form.result }</p>
                 <c:choose>
        			<c:when test="${ !requestScope.modify eq modif }">
        				<input type="submit" name = "Create" value="Create"  /> 			
        			</c:when>
        			<c:otherwise>
        				<input type="submit" name="Create" value="Modify"  />
        			</c:otherwise>
        		</c:choose>
                <input type="reset" value="Reset all" /> <br />
            </form>
        </div>
    </body>
</html>

WebContent/WEB-INF/displayPrivs.jsp
<%-- This page displays all privileges created and stored in database --%>

<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Privilege list</title>
        <link type="text/css" rel="stylesheet" href="<c:url value="/inc/design.css"/>" />
    </head>
    <body>
        <c:import url="/inc/menu.jsp" />
        
        <div id="normalFormPriv">
        <h1>Privileges  </h1>
        <br />
        <c:choose>
            <%-- If there is no privilege in database--%>
            <c:when test="${ empty requestScope.privs }">
                <p class="erreur">No privileges</p>
            </c:when>
            <%-- Else, table is displayed --%>
            <c:otherwise>
            <CENTER> 
            <table>
                <tr>
                	<th>Privilege name</th>
                    <th>Description</th>
                    <th>Menus</th>
                    <th class="action">Modify</th>
                    <th class="action">Delete</th>                   
                </tr>
                <%--A test to put a different color every other time  --%>
                <c:forEach items="${ requestScope.privs }" var="mapPrivs" varStatus="boucle">
                <tr class="${boucle.index % 2 == 0 ? 'pair' : 'impair'}">
                    <td><c:out value="${ mapPrivs.value.privName }"/></td>
                    <td><c:out value="${ mapPrivs.value.privDescription }"/></td>
                    <td>
	                    <c:forEach items="${mapPrivs.value.menuNames}" var="item">
						    ${item} / 
						</c:forEach>
					</td>
					<td class="action">
                        <a href="<c:url value="/privCreation"><c:param name="privName" value="${ mapPrivs.value.privName }" /><c:param name="modify" value="true" /></c:url>">
                            <img src="<c:url value="/inc/modify.gif"/>" alt="mod" />
                        </a>
                    </td>
                    <td class="action">
                        <a href="<c:url value="/deletePriv"><c:param name="privName" value="${ mapPrivs.value.privName }" /></c:url>">
                            <img src="<c:url value="/inc/supprimer.png"/>" alt="Delete" />
                        </a>
                    </td>
                </tr>
                </c:forEach>
            </table>
            </CENTER>
            </c:otherwise>
        </c:choose>
        </div>
    </body>
</html>